const CONFIG = {
    OPENAI_API_KEY: "YOUR_OPENAI_API_KEY_HERE",
    EMAILJS_SERVICE_ID: "YOUR_SERVICE_ID_HERE",
    EMAILJS_TEMPLATE_ID: "YOUR_TEMPLATE_ID_HERE",
    EMAILJS_PUBLIC_KEY: "YOUR_PUBLIC_KEY_HERE",
    SUPABASE_URL: "YOUR_SUPABASE_URL_HERE",
    SUPABASE_KEY: "YOUR_SUPABASE_KEY_HERE",
    WEATHER_API_KEY: "YOUR_WEATHERAPI_KEY",
    GEMINI_API_KEY: "YOUR_GEMINI_API_KEY_HERE"
};
